# Generated by Django 3.0.5 on 2020-04-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupin', '0003_auto_20200417_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFSchedules',
            fields=[
                ('cid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
