# Generated by Django 3.0.5 on 2020-07-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupin', '0004_cfschedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfschedules',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cfschedules',
            name='time',
            field=models.TimeField(),
        ),
    ]
